### ISSUE TITLE
你好，这个能否用于arm架构服务器jumpserver的部署

### ISSUE THREAD

**Issue by ascarl2010** [pvtmert/static-docker#1]
你好，这个能否用于arm架构服务器jumpserver的部署

**Comment by spacelatte** [comment]
Hello,

Sorry I don't speak Chineese but as far as I understand (using google translate) you can use the image in the DockerHub directly: https://hub.docker.com/r/pvtmert/jumpserver/tags

I'm making all images available in different architectures but DockerHub's build system does not support other than intel/x86.

So, I've migrated them to GitHub actions, since cache is missing at the initial step. It's taking a while to generate them all. (Also some of the images require some updates)
